Fix compile error on targets with unsigned char
abc is failing to compile on ppc64le because char is unsigned by
default:

src/misc/extra/extraUtilMisc.c: In function ‘void abc::Extra_TruthExpand(int, int, unsigned int*, unsigned int, unsigned int*)’:
src/misc/extra/extraUtilMisc.c:1550:5: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]